[package]
name = "leptos_hydrated_macro"
version = "0.1.0"
edition = "2024"
authors = ["David Darrell"]
license = "MIT"
description = "Procedural macros for the leptos_hydrated library"
repository = "https://github.com/incon/leptos_hydrated"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
